# Settings
$text_color = rgba(255, 255, 255, 0.5)
$entry_background_color = rgba(49, 49, 49, 0.1)
$entry_border_color = rgba(142, 142, 142, 0.5)
$entry_color = rgb(255, 255, 255)
$fail_color = rgb(255, 0, 0)
$check_color = rgb(0, 255, 0)
$caps_color = rgb(255, 255, 0)
$font_family = Google Sans Flex Medium
$font_family_clock = Google Sans Flex Medium
$font_material_symbols = Material Symbols Rounded

# Animation
animation {
    bezier = linear, 1, 1, 0, 0
    animation = fade, 1, 1.8, linear
}

# Background
background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 4
}

# Password Input
input-field {
    monitor =
    size = 320, 40
    outline_thickness = 1
    dots_size = 0.1
    dots_spacing = 0.5
    outer_color = $entry_border_color
    inner_color = $entry_background_color
    capslock_color = $caps_color
    check_color = $check_color
    font_color = $entry_color
    fade_on_empty = false

    placeholder_text = Enter Password
    fail_text = Incorrect Password

    position = 0, 25
    halign = center
    valign = bottom
}

# Caps Lock Warning
label {
    monitor =
    text = cmd[update:50] ${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hyprlock/check-capslock.sh
    color = $text_color
    font_size = 11
    font_family = $font_family
    position = 0, 80
    halign = center
    valign = bottom
}

# Clock
label {
    monitor =
    text = $TIME
    color = $text_color
    font_size = 65
    font_family = $font_family_clock

    position = 0, -100
    halign = center
    valign = top
}

# Date
label {
    monitor =
    text = cmd[update:5000] date +"%A, %B %d"
    color = $text_color
    font_size = 17
    font_family = $font_family_clock

    position = 0, -200
    halign = center
    valign = top
}
